### PR TITLE
Fix incorrect behaviour with INT_MAX pmpaddr

### LINKED ISSUE #739: Incorrect behaviour with INT_MAX pmpaddr
If you set `pmpaddr` to `ones()` then it will misbehave. For NAPOT it will return `(zeros(), zeros())`. For NA4 it will return `(ones(), zeros())`. In both cases it will match no addresses, whereas it should match all memory, or the top 4 bytes respectively.

I have a fix for this, and a test (I know!). The test is written in Zig... I was experimenting with that. I'll demo it in the next meeting I'm at (24th).

### PR DESCRIPTION
**Pull request by Timmmm**
This fixes a bug if you set `pmpaddr` to `ones()`. For NAPOT it would return `(zeros(), zeros())`. For NA4 it would return `(ones(), zeros())`. In both cases it will match no addresses, whereas it should match all memory, or the top 4 bytes respectively.

A test is included for NAPOT that fails before and passes afterwards.

Fixes #739

### CODE REVIEW

**Review by pmundkur — APPROVED** [review]
LGTM.

The `it` in `it would return` in the commit message wasn't clear.  It may help to also clarify that the overflow problem was solved by converting to `nat` before doing range arithmetic.

File: test/first_party/src/test_max_pmp.c [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  asm volatile("csrc mstatus, %[mpp];"
+               "csrs mstatus, %[mprv];"
+               :
+               : [mpp] "r"(mpp), [mprv] "r"(mprv));
+
+  uint_xlen_t pmpcfg_napot = PMPCFG_NAPOT | PMPCFG_X | PMPCFG_W | PMPCFG_R;
+
+  asm volatile("csrw pmpcfg0, %[cfg]" : : [cfg] "r"(pmpcfg_napot));
+
+  // Access memory to test loads/stores.
```
Comment (arichardson) [inline test/first_party/src/test_max_pmp.c:38]: Add a volatile load of some global volatile variable here instead of relying on printf side effects?

**Review by arichardson — COMMENTED** [review]
Did not review the sail change in detail but it looks reasonable. One small comment on the test, but overall this lgtm

File: test/first_party/src/test_max_pmp.c (hunk 1 above)
Comment (Timmmm) [reply test/first_party/src/test_max_pmp.c:38]: Will do.

Comment (Timmmm) [reply test/first_party/src/test_max_pmp.c:40]: Done.

**Review by arichardson — APPROVED** [review]
